### ISSUE TITLE
charset issue

### ISSUE THREAD

**Issue by millette** [pfrazee/example-self-mutating-dat-site#1]
After a few mutations I got this response:
```
Self-mutated at 6/8/2017, 11:07:01 AM
Self-mutated at 09/06/2017 Ã  15:03:59
Self-mutated at 09/06/2017 Ã  15:04:04
Self-mutated at 09/06/2017 à 15:07:11
```

Last line wasn't *saved* (published) yet, but then I do, the "à" is converted to "Ã"

Probably related to the beaker issue regarding utf-8.

**Comment by pfrazee** [comment]
Thanks, that's intriguing.

**Comment by millette** [comment]
The output of 
```js
new Date().toLocaleString()
```
can be a bit surprising. I'm getting "09/06/2017 à 15:16:34" in the beaker js console and "2017-06-09 15:15:27" in Firefox.

It's probably related to https://github.com/beakerbrowser/beaker/issues/499 where the default charset appears to be windows-1252.

**Comment by pfrazee** [comment]
Yeah, I think I can probably control the default charsets with some
response headers in the Dat protocol. I'll use Date's string() to help me
test. Appreciate that observation

**Comment by millette** [comment]
This works now, with the added meta charset: <dat://879ab97007fa1d57b77b423a4eb3efb6279d98f9ed9d30b510885c42fbbe54ff/>
